import type { AppState } from "./types";
import { DEMO_PASSWORD, GIS_DATASET } from "./constants";
import { seedTerritories } from "./territory-seed";
import { demoLinks } from "./ezc-index";

const now = new Date("2026-09-02T08:00:00+02:00");
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return iso(d);
};
const daysAhead = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return iso(d);
};

export function createDemoState(): AppState {
  return {
    settings: {
      defaultGeofenceRadius: 80,
      organizationName: "One Voice 27",
      conferenceName: "East Zimbabwe Conference",
      divisionName: "Southern Africa-Indian Ocean Division",
      requireGeofence: true,
      exceptionRequiresApproval: true,
      allowTrainingLocation: true,
      gisDataset: GIS_DATASET,
    },
    regions: [
      { id: "reg_harare", name: "Harare", conference: "East Zimbabwe Conference" },
      { id: "reg_chitungwiza", name: "Chitungwiza District", conference: "East Zimbabwe Conference" },
    ],
    territories: seedTerritories(),
    churches: [
      {
        id: "ch_central",
        name: "Harare Central SDA Church",
        regionId: "reg_harare",
        districtId: demoLinks.harareCentralDistrictId,
        territoryId: demoLinks.centralChurchTerritoryId,
        address: "Corner Second Street & Speke Avenue",
        city: "Harare",
        lat: -17.8292,
        lng: 31.0522,
      },
      {
        id: "ch_waterfalls",
        name: "Waterfalls SDA Church",
        regionId: "reg_harare",
        districtId: demoLinks.waterfallsDistrictId,
        territoryId: demoLinks.waterfallsChurchTerritoryId,
        address: "Highfield Road, Waterfalls",
        city: "Harare",
        lat: -17.8774,
        lng: 31.0341,
      },
      {
        id: "ch_eastview",
        name: "Eastview SDA Church",
        regionId: "reg_harare",
        districtId: demoLinks.highlandsDistrictId,
        territoryId: demoLinks.eastviewChurchTerritoryId,
        address: "Enterprise Road, Highlands",
        city: "Harare",
        lat: -17.7881,
        lng: 31.0918,
      },
    ],
    users: [
      {
        id: "usr_master",
        email: "master@onevoice27.org",
        password: DEMO_PASSWORD,
        displayName: "Dr. N. Debelem",
        role: "master_admin",
        churchIds: ["ch_central", "ch_waterfalls", "ch_eastview"],
        territoryIds: [demoLinks.conferenceId],
        phone: "+263 77 000 0001",
        title: "Conference Personal Ministries",
        status: "active",
      },
      {
        id: "usr_admin_central",
        email: "admin.harare@onevoice27.org",
        password: DEMO_PASSWORD,
        displayName: "Elder Chipo Nyathi",
        role: "church_admin",
        churchIds: ["ch_central"],
        territoryIds: [demoLinks.harareCentralDistrictId, demoLinks.centralChurchTerritoryId],
        phone: "+263 77 000 0002",
        title: "Church Clerk",
        status: "active",
      },
      {
        id: "usr_pastor_tendai",
        email: "pastor.tendai@onevoice27.org",
        password: DEMO_PASSWORD,
        displayName: "Pastor Tendai Moyo",
        role: "pastor",
        churchIds: ["ch_central"],
        territoryIds: [demoLinks.harareCentralDistrictId, demoLinks.centralChurchTerritoryId],
        phone: "+263 77 111 2201",
        title: "District Pastor",
        status: "active",
      },
      {
        id: "usr_pastor_grace",
        email: "pastor.grace@onevoice27.org",
        password: DEMO_PASSWORD,
        displayName: "Pastor Grace Ncube",
        role: "pastor",
        churchIds: ["ch_waterfalls"],
        territoryIds: [demoLinks.waterfallsDistrictId, demoLinks.waterfallsChurchTerritoryId],
        phone: "+263 77 111 2202",
        title: "Associate Pastor",
        status: "active",
      },
      {
        id: "usr_pastor_john",
        email: "pastor.john@onevoice27.org",
        password: DEMO_PASSWORD,
        displayName: "Pastor John Chikwanha",
        role: "pastor",
        churchIds: ["ch_eastview"],
        territoryIds: [demoLinks.highlandsDistrictId, demoLinks.eastviewChurchTerritoryId],
        phone: "+263 77 111 2203",
        title: "District Pastor",
        status: "active",
      },
    ],
    categories: [
      {
        id: "cat_pastoral",
        name: "Pastoral Visitation",
        description: "Spiritual care, prayer, encouragement, discipleship and family support.",
        active: true,
        color: "#e400ff",
      },
      {
        id: "cat_general",
        name: "General Visitation",
        description: "Routine member engagement, welfare checks and relationship building.",
        active: true,
        color: "#9eecff",
      },
      {
        id: "cat_stewardship",
        name: "Stewardship Visitation",
        description: "Stewardship education, faithfulness and church support conversations.",
        active: true,
        color: "#ffc24a",
      },
      {
        id: "cat_crisis",
        name: "Crisis Visitation",
        description: "Bereavement, illness, emergency or family crisis.",
        active: true,
        color: "#ff5d7a",
      },
      {
        id: "cat_new",
        name: "New Member Visitation",
        description: "Newly baptized, transferred or newly registered members.",
        active: true,
        color: "#5dffb2",
      },
      {
        id: "cat_followup",
        name: "Follow-Up Visitation",
        description: "Reconnect with inactive members or digital Bible-study interests.",
        active: true,
        color: "#7aa8ff",
      },
      {
        id: "cat_other",
        name: "Other",
        description: "Administrator-configurable purpose.",
        active: true,
        color: "#c9b8ff",
      },
    ],
    members: [
      {
        id: "mem_jane",
        firstName: "Jane",
        lastName: "Doe",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1101",
        email: "jane.doe@example.com",
        address: "12 Borrowdale Brook, Gunhill",
        suburb: "Gunhill",
        lat: -17.7845,
        lng: 31.0712,
        geofenceRadius: 80,
        visitationFrequency: "quarterly",
        lastVisitAt: daysAgo(90),
        nextVisitDue: daysAhead(3),
        memberType: "regular",
        status: "active",
        createdAt: daysAgo(400),
      },
      {
        id: "mem_mary",
        firstName: "Mary",
        lastName: "Brown",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1102",
        address: "44 Samora Machel Avenue, Eastlea",
        suburb: "Eastlea",
        lat: -17.8241,
        lng: 31.0664,
        geofenceRadius: 70,
        visitationFrequency: "monthly",
        lastVisitAt: daysAgo(48),
        nextVisitDue: daysAgo(18),
        memberType: "followup",
        adminNotes: "Has not attended since June. Requested prayer for employment.",
        status: "active",
        createdAt: daysAgo(800),
      },
      {
        id: "mem_tawanda",
        firstName: "Tawanda",
        lastName: "Sibanda",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1103",
        address: "8 Lomagundi Road, Avondale",
        suburb: "Avondale",
        lat: -17.8033,
        lng: 31.0358,
        geofenceRadius: 60,
        visitationFrequency: "monthly",
        lastVisitAt: daysAgo(5),
        nextVisitDue: daysAhead(25),
        memberType: "new",
        baptizedAt: daysAgo(21),
        status: "active",
        createdAt: daysAgo(40),
      },
      {
        id: "mem_rudo",
        firstName: "Rudo",
        lastName: "Mhlanga",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1104",
        address: "19 Arcturus Road, Greendale",
        suburb: "Greendale",
        lat: -17.8188,
        lng: 31.0981,
        geofenceRadius: 90,
        visitationFrequency: "bimonthly",
        lastVisitAt: daysAgo(70),
        nextVisitDue: daysAgo(10),
        memberType: "crisis",
        adminNotes: "Family bereavement — father passed 12 August.",
        status: "active",
        createdAt: daysAgo(1200),
      },
      {
        id: "mem_joseph",
        firstName: "Joseph",
        lastName: "Dube",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1105",
        address: "3 Livingstone Avenue, Belgravia",
        suburb: "Belgravia",
        lat: -17.7989,
        lng: 31.0442,
        geofenceRadius: 75,
        visitationFrequency: "quarterly",
        lastVisitAt: daysAgo(20),
        nextVisitDue: daysAhead(70),
        memberType: "regular",
        status: "active",
        createdAt: daysAgo(500),
      },
      {
        id: "mem_anita",
        firstName: "Anita",
        lastName: "Chigumba",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1106",
        address: "67 Churchill Avenue, Alexandra Park",
        suburb: "Alexandra Park",
        lat: -17.7912,
        lng: 31.0477,
        geofenceRadius: 80,
        visitationFrequency: "monthly",
        lastVisitAt: daysAgo(28),
        nextVisitDue: daysAhead(2),
        memberType: "regular",
        status: "active",
        createdAt: daysAgo(300),
      },
      {
        id: "mem_peter",
        firstName: "Peter",
        lastName: "Ncube",
        churchId: "ch_waterfalls",
        assignedPastorId: "usr_pastor_grace",
        phone: "+263 77 301 2201",
        address: "21 Main Street, Waterfalls",
        suburb: "Waterfalls",
        lat: -17.8712,
        lng: 31.0294,
        geofenceRadius: 100,
        visitationFrequency: "monthly",
        lastVisitAt: daysAgo(40),
        nextVisitDue: daysAgo(10),
        memberType: "followup",
        status: "active",
        createdAt: daysAgo(600),
      },
      {
        id: "mem_lindiwe",
        firstName: "Lindiwe",
        lastName: "Khumalo",
        churchId: "ch_waterfalls",
        assignedPastorId: "usr_pastor_grace",
        phone: "+263 77 301 2202",
        address: "14 Gugulethu Close, Highfield",
        suburb: "Highfield",
        lat: -17.8834,
        lng: 31.0188,
        geofenceRadius: 70,
        visitationFrequency: "quarterly",
        lastVisitAt: daysAgo(12),
        nextVisitDue: daysAhead(78),
        memberType: "new",
        baptizedAt: daysAgo(18),
        status: "active",
        createdAt: daysAgo(25),
      },
      {
        id: "mem_samuel",
        firstName: "Samuel",
        lastName: "Makoni",
        churchId: "ch_eastview",
        assignedPastorId: "usr_pastor_john",
        phone: "+263 77 401 3301",
        address: "9 Ridgeway North, Highlands",
        suburb: "Highlands",
        lat: -17.7866,
        lng: 31.0884,
        geofenceRadius: 85,
        visitationFrequency: "bimonthly",
        lastVisitAt: daysAgo(55),
        nextVisitDue: daysAgo(0),
        memberType: "regular",
        status: "active",
        createdAt: daysAgo(900),
      },
      {
        id: "mem_blessing",
        firstName: "Blessing",
        lastName: "Mutasa",
        churchId: "ch_eastview",
        assignedPastorId: "usr_pastor_john",
        phone: "+263 77 401 3302",
        address: "4 The Chase, Mount Pleasant",
        suburb: "Mount Pleasant",
        lat: -17.7761,
        lng: 31.0549,
        geofenceRadius: 80,
        visitationFrequency: "monthly",
        lastVisitAt: daysAgo(33),
        nextVisitDue: daysAgo(3),
        memberType: "crisis",
        adminNotes: "Hospital follow-up after surgery.",
        status: "active",
        createdAt: daysAgo(220),
      },
      {
        id: "mem_chiedza",
        firstName: "Chiedza",
        lastName: "Gumbo",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1107",
        address: "88 Kwame Nkrumah Avenue",
        suburb: "CBD",
        lat: -17.8319,
        lng: 31.0491,
        geofenceRadius: 50,
        visitationFrequency: "monthly",
        lastVisitAt: daysAgo(8),
        nextVisitDue: daysAhead(22),
        memberType: "regular",
        status: "active",
        createdAt: daysAgo(150),
      },
      {
        id: "mem_farai",
        firstName: "Farai",
        lastName: "Banda",
        churchId: "ch_central",
        assignedPastorId: "usr_pastor_tendai",
        phone: "+263 77 201 1108",
        address: "15 Cork Road, Belvedere",
        suburb: "Belvedere",
        lat: -17.8215,
        lng: 31.0218,
        geofenceRadius: 80,
        visitationFrequency: "quarterly",
        lastVisitAt: daysAgo(100),
        nextVisitDue: daysAgo(10),
        memberType: "inactive",
        adminNotes: "Digital interest from #AllThingsNew — requested Bible study.",
        status: "active",
        createdAt: daysAgo(14),
      },
    ],
    visits: [
      {
        id: "vis_001",
        memberId: "mem_tawanda",
        pastorId: "usr_pastor_tendai",
        churchId: "ch_central",
        categoryId: "cat_new",
        status: "completed",
        completedAt: daysAgo(5),
        geofenceEnteredAt: daysAgo(5),
        lat: -17.8034,
        lng: 31.0359,
        accuracy: 12,
        locationVerification: "verified",
        geofenceStatus: "entered",
        adminNotes: "Welcome visit after baptism. Family prayed together.",
        followUpRequired: false,
        referralRequired: false,
        prayed: true,
        bibleStudy: true,
        durationMinutes: 48,
        createdAt: daysAgo(5),
      },
      {
        id: "vis_002",
        memberId: "mem_chiedza",
        pastorId: "usr_pastor_tendai",
        churchId: "ch_central",
        categoryId: "cat_pastoral",
        status: "completed",
        completedAt: daysAgo(8),
        geofenceEnteredAt: daysAgo(8),
        lat: -17.8317,
        lng: 31.049,
        accuracy: 9,
        locationVerification: "verified",
        geofenceStatus: "entered",
        followUpRequired: false,
        referralRequired: false,
        prayed: true,
        durationMinutes: 35,
        createdAt: daysAgo(8),
      },
      {
        id: "vis_003",
        memberId: "mem_lindiwe",
        pastorId: "usr_pastor_grace",
        churchId: "ch_waterfalls",
        categoryId: "cat_new",
        status: "completed",
        completedAt: daysAgo(12),
        geofenceEnteredAt: daysAgo(12),
        lat: -17.8835,
        lng: 31.0189,
        accuracy: 18,
        locationVerification: "verified",
        geofenceStatus: "entered",
        followUpRequired: true,
        nextVisitRecommendation: "Invite to small group in two weeks.",
        referralRequired: false,
        prayed: true,
        bibleStudy: true,
        baptismInterest: true,
        durationMinutes: 55,
        createdAt: daysAgo(12),
      },
      {
        id: "vis_004",
        memberId: "mem_blessing",
        pastorId: "usr_pastor_john",
        churchId: "ch_eastview",
        categoryId: "cat_crisis",
        status: "exception_pending",
        completedAt: daysAgo(1),
        lat: -17.801,
        lng: 31.06,
        accuracy: 40,
        locationVerification: "unverified",
        geofenceStatus: "not_entered",
        exceptionReason: "Visited at Parirenyatwa Hospital — member not at registered residence.",
        adminNotes: "Prayed with family in surgical ward.",
        followUpRequired: true,
        referralRequired: true,
        prayed: true,
        referred: true,
        urgency: "high",
        durationMinutes: 40,
        createdAt: daysAgo(1),
      },
      {
        id: "vis_005",
        memberId: "mem_jane",
        pastorId: "usr_pastor_tendai",
        churchId: "ch_central",
        categoryId: "cat_pastoral",
        status: "completed",
        completedAt: daysAgo(2),
        geofenceEnteredAt: daysAgo(2),
        lat: -17.825,
        lng: 31.04,
        accuracy: 6,
        locationVerification: "verified",
        geofenceStatus: "entered",
        trainingOverride: true,
        adminNotes: "Geofence training at the office — not a field visit.",
        followUpRequired: false,
        referralRequired: false,
        durationMinutes: 12,
        createdAt: daysAgo(2),
      },
      {
        id: "vis_006",
        memberId: "mem_peter",
        pastorId: "usr_pastor_grace",
        churchId: "ch_waterfalls",
        categoryId: "cat_pastoral",
        status: "completed",
        completedAt: daysAgo(6),
        geofenceEnteredAt: daysAgo(6),
        lat: -17.8774,
        lng: 31.0341,
        accuracy: 14,
        locationVerification: "verified",
        geofenceStatus: "entered",
        followUpRequired: false,
        referralRequired: false,
        durationMinutes: 22,
        createdAt: daysAgo(6),
      },
    ],
    notifications: [
      {
        id: "nt_1",
        userId: "usr_pastor_tendai",
        title: "3 members due this week",
        body: "Jane Doe, Anita Chigumba and Rudo Mhlanga need pastoral care.",
        type: "due",
        read: false,
        createdAt: daysAgo(0),
        href: "/schedule",
      },
      {
        id: "nt_2",
        userId: "usr_pastor_tendai",
        title: "Crisis visit outstanding",
        body: "Rudo Mhlanga’s family is in bereavement. Visit is 10 days overdue.",
        type: "overdue",
        read: false,
        createdAt: daysAgo(1),
        href: "/go/mem_rudo",
      },
      {
        id: "nt_3",
        userId: "usr_master",
        title: "Manual verification waiting",
        body: "Pastor John requested exception approval for Blessing Mutasa (hospital visit).",
        type: "exception",
        read: false,
        createdAt: daysAgo(1),
        href: "/exceptions",
      },
      {
        id: "nt_4",
        userId: "usr_pastor_john",
        title: "Exception submitted",
        body: "Your hospital visit for Blessing Mutasa is awaiting administrator approval.",
        type: "exception",
        read: true,
        createdAt: daysAgo(1),
        href: "/exceptions",
      },
    ],
    audit: [
      {
        id: "aud_1",
        actorId: "usr_pastor_tendai",
        actorName: "Pastor Tendai Moyo",
        action: "visit.completed",
        entityType: "visit",
        entityId: "vis_001",
        metadata: { member: "Tawanda Sibanda", verification: "verified" },
        createdAt: daysAgo(5),
      },
      {
        id: "aud_2",
        actorId: "usr_pastor_john",
        actorName: "Pastor John Chikwanha",
        action: "visit.exception_requested",
        entityType: "visit",
        entityId: "vis_004",
        metadata: { reason: "Hospital visit" },
        createdAt: daysAgo(1),
      },
    ],
  };
}
